version: '3.8'

services:
  web:
    container_name: django
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always  
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        gunicorn core.wsgi:application --bind 0.0.0.0:8000 --timeout 600 --workers 4 --threads 4
      "
    volumes:
      - static:/backend/static
      - media:/backend/media 
    expose:
      - 8000
    env_file:
      - ./backend/.env
    depends_on:
      - db
    
    healthcheck:
        test: ["CMD", "curl", "-f", "http://web:8000"]
        interval: 30s
        timeout: 10s
        retries: 5
    networks:
       - app-network

  db:
    container_name: db
    image: postgres:16.2
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432
    networks:
       - app-network

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    volumes:
      - static:/backend/static
      - media:/backend/media
    ports:
      - 80:80
    depends_on:
      - web
      - vue
    networks:
       - app-network

  vue:
    build: ./frontend
    ports:
      - "8081:8080"
    environment:
      VUE_APP_API_URL: "http://localhost"
    depends_on:
      - db
    networks:
       - app-network

volumes:
  postgres_data:
  static:
  media:

networks:
  app-network: